In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('Wednesday-workingHours.pcap_ISCX.csv')

In [3]:
df.columns

Index([' Destination Port', ' Flow Duration', ' Total Fwd Packets',
       ' Total Backward Packets', 'Total Length of Fwd Packets',
       ' Total Length of Bwd Packets', ' Fwd Packet Length Max',
       ' Fwd Packet Length Min', ' Fwd Packet Length Mean',
       ' Fwd Packet Length Std', 'Bwd Packet Length Max',
       ' Bwd Packet Length Min', ' Bwd Packet Length Mean',
       ' Bwd Packet Length Std', 'Flow Bytes/s', ' Flow Packets/s',
       ' Flow IAT Mean', ' Flow IAT Std', ' Flow IAT Max', ' Flow IAT Min',
       'Fwd IAT Total', ' Fwd IAT Mean', ' Fwd IAT Std', ' Fwd IAT Max',
       ' Fwd IAT Min', 'Bwd IAT Total', ' Bwd IAT Mean', ' Bwd IAT Std',
       ' Bwd IAT Max', ' Bwd IAT Min', 'Fwd PSH Flags', ' Bwd PSH Flags',
       ' Fwd URG Flags', ' Bwd URG Flags', ' Fwd Header Length',
       ' Bwd Header Length', 'Fwd Packets/s', ' Bwd Packets/s',
       ' Min Packet Length', ' Max Packet Length', ' Packet Length Mean',
       ' Packet Length Std', ' Packet Length Variance', '

In [4]:
df.head()

Destination Port   Flow Duration   Total Fwd Packets  \
0                 80           38308                   1   
1                389             479                  11   
2                 88            1095                  10   
3                389           15206                  17   
4                 88            1092                   9   

    Total Backward Packets  Total Length of Fwd Packets  \
0                        1                            6   
1                        5                          172   
2                        6                         3150   
3                       12                         3452   
4                        6                         3150   

    Total Length of Bwd Packets   Fwd Packet Length Max  \
0                             6                       6   
1                           326                      79   
2                          3150                    1575   
3                          6660                    1313   
4                          3152                    1575   

    Fwd Packet Length Min   Fwd Packet Length Mean   Fwd Packet Length Std  \
0                       6                 6.000000                0.000000   
1                       0                15.636364               31.449238   
2                       0               315.000000              632.561635   
3                       0               203.058823              425.778474   
4                       0               350.000000              694.509719   

   ...   min_seg_size_forward  Active Mean   Active Std   Active Max  \
0  ...                     20          0.0          0.0            0   
1  ...                     32          0.0          0.0            0   
2  ...                     32          0.0          0.0            0   
3  ...                     32          0.0          0.0            0   
4  ...                     32          0.0          0.0            0   

    Active Min  Idle Mean   Idle Std   Idle Max   Idle Min   Label  
0            0        0.0        0.0          0          0  BENIGN  
1            0        0.0        0.0          0          0  BENIGN  
2            0        0.0        0.0          0          0  BENIGN  
3            0        0.0        0.0          0          0  BENIGN  
4            0        0.0        0.0          0          0  BENIGN  

[5 rows x 79 columns]

In [5]:
df.isnull().sum()

 Destination Port              0
 Flow Duration                 0
 Total Fwd Packets             0
 Total Backward Packets        0
Total Length of Fwd Packets    0
                              ..
Idle Mean                      0
 Idle Std                      0
 Idle Max                      0
 Idle Min                      0
 Label                         0
Length: 79, dtype: int64

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 692703 entries, 0 to 692702
Data columns (total 79 columns):
 #   Column                        Non-Null Count   Dtype  
---  ------                        --------------   -----  
 0    Destination Port             692703 non-null  int64  
 1    Flow Duration                692703 non-null  int64  
 2    Total Fwd Packets            692703 non-null  int64  
 3    Total Backward Packets       692703 non-null  int64  
 4   Total Length of Fwd Packets   692703 non-null  int64  
 5    Total Length of Bwd Packets  692703 non-null  int64  
 6    Fwd Packet Length Max        692703 non-null  int64  
 7    Fwd Packet Length Min        692703 non-null  int64  
 8    Fwd Packet Length Mean       692703 non-null  float64
 9    Fwd Packet Length Std        692703 non-null  float64
 10  Bwd Packet Length Max         692703 non-null  int64  
 11   Bwd Packet Length Min        692703 non-null  int64  
 12   Bwd Packet Length Mean       692703 non-nul

In [7]:
df

Destination Port   Flow Duration   Total Fwd Packets  \
0                      80           38308                   1   
1                     389             479                  11   
2                      88            1095                  10   
3                     389           15206                  17   
4                      88            1092                   9   
...                   ...             ...                 ...   
692698                 53           32215                   4   
692699                 53             324                   2   
692700              58030              82                   2   
692701                 53         1048635                   6   
692702                 53           94939                   4   

         Total Backward Packets  Total Length of Fwd Packets  \
0                             1                            6   
1                             5                          172   
2                             6                         3150   
3                            12                         3452   
4                             6                         3150   
...                         ...                          ...   
692698                        2                          112   
692699                        2                           84   
692700                        1                           31   
692701                        2                          192   
692702                        2                          188   

         Total Length of Bwd Packets   Fwd Packet Length Max  \
0                                  6                       6   
1                                326                      79   
2                               3150                    1575   
3                               6660                    1313   
4                               3152                    1575   
...                              ...                     ...   
692698                           152                      28   
692699                           362                      42   
692700                             6                      31   
692701                           256                      32   
692702                           226                      47   

         Fwd Packet Length Min   Fwd Packet Length Mean  \
0                            6                 6.000000   
1                            0                15.636364   
2                            0               315.000000   
3                            0               203.058823   
4                            0               350.000000   
...                        ...                      ...   
692698                      28                28.000000   
692699                      42                42.000000   
692700                       0                15.500000   
692701                      32                32.000000   
692702                      47                47.000000   

         Fwd Packet Length Std  ...   min_seg_size_forward  Active Mean  \
0                     0.000000  ...                     20          0.0   
1                    31.449238  ...                     32          0.0   
2                   632.561635  ...                     32          0.0   
3                   425.778474  ...                     32          0.0   
4                   694.509719  ...                     32          0.0   
...                        ...  ...                    ...          ...   
692698                0.000000  ...                     20          0.0   
692699                0.000000  ...                     20          0.0   
692700               21.920310  ...                     32          0.0   
692701                0.000000  ...                     20          0.0   
692702                0.000000  ...                     20          0.0   

         Active Std   Active Max   Active Min  Idle Mean   Idle Std  \
0        

In [8]:
df.corr()

/var/folders/91/f1vtq1sj1ns161qv6d_3lf3m0000gn/T/ipykernel_32782/1134722465.py:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.corr()


Destination Port   Flow Duration  \
 Destination Port                     1.000000       -0.196766   
 Flow Duration                       -0.196766        1.000000   
 Total Fwd Packets                   -0.003484        0.014660   
 Total Backward Packets              -0.003255        0.013723   
Total Length of Fwd Packets           0.015119        0.082203   
...                                        ...             ...   
 Active Min                          -0.035320        0.064672   
Idle Mean                            -0.169666        0.874839   
 Idle Std                            -0.031716        0.185234   
 Idle Max                            -0.171340        0.884918   
 Idle Min                            -0.166871        0.858641   

                              Total Fwd Packets   Total Backward Packets  \
 Destination Port                     -0.003484                -0.003255   
 Flow Duration                         0.014660                 0.013723   
 Total Fwd Packets                     1.000000                 0.998900   
 Total Backward Packets                0.998900                 1.000000   
Total Length of Fwd Packets            0.726200                 0.725553   
...                                         ...                      ...   
 Active Min                            0.004765                 0.004616   
Idle Mean                             -0.000697                -0.001095   
 Idle Std                              0.000592                 0.000141   
 Idle Max                             -0.000621                -0.001083   
 Idle Min                             -0.000779                -0.001133   

                             Total Length of Fwd Packets  \
 Destination Port                               0.015119   
 Flow Duration                                  0.082203   
 Total Fwd Packets                              0.726200   
 Total Backward Packets                         0.725553   
Total Length of Fwd Packets                     1.000000   
...                                                  ...   
 Active Min                                     0.067483   
Idle Mean                                       0.021046   
 Idle Std                                       0.012873   
 Idle Max                                       0.022572   
 Idle Min                                       0.019556   

                              Total Length of Bwd Packets  \
 Destination Port                               -0.002659   
 Flow Duration                                   0.011720   
 Total Fwd Packets                               0.995874   
 Total Backward Packets                          0.992630   
Total Length of Fwd Packets                      0.720451   
...                                                   ...   
 Active Min                                      0.003361   
Idle Mean                                       -0.000916   
 Idle Std                                       -0.000090   
 Idle Max                                       -0.000927   
 Idle Min                                       -0.000917   

                              Fwd Packet Length Max   Fwd Packet Length Min  \
 Destination Port                          0.070528               -0.070202   
 Flow Duration                             0.306022               -0.173684   
 Total Fwd Packets                         0.008358               -0.002939   
 Total Backward Packets                    0.007951               -0.002556   
Total Length of Fwd Packets                0.319972               -0.004604   
...                                             ...                     ...   
 Active Min                                0.033738               -0.026594   
Idle Mean                                  0.226709               -0.153108   
 Idle Std                                  0.025502               -0.027049   
 Idle Max                                  0.226607               -0.154454   
 

In [9]:

from sklearn.preprocessing import LabelEncoder

In [10]:
encoder = LabelEncoder()
df[' Label']=encoder.fit_transform(df[' Label'])

In [11]:
df.head()

Destination Port   Flow Duration   Total Fwd Packets  \
0                 80           38308                   1   
1                389             479                  11   
2                 88            1095                  10   
3                389           15206                  17   
4                 88            1092                   9   

    Total Backward Packets  Total Length of Fwd Packets  \
0                        1                            6   
1                        5                          172   
2                        6                         3150   
3                       12                         3452   
4                        6                         3150   

    Total Length of Bwd Packets   Fwd Packet Length Max  \
0                             6                       6   
1                           326                      79   
2                          3150                    1575   
3                          6660                    1313   
4                          3152                    1575   

    Fwd Packet Length Min   Fwd Packet Length Mean   Fwd Packet Length Std  \
0                       6                 6.000000                0.000000   
1                       0                15.636364               31.449238   
2                       0               315.000000              632.561635   
3                       0               203.058823              425.778474   
4                       0               350.000000              694.509719   

   ...   min_seg_size_forward  Active Mean   Active Std   Active Max  \
0  ...                     20          0.0          0.0            0   
1  ...                     32          0.0          0.0            0   
2  ...                     32          0.0          0.0            0   
3  ...                     32          0.0          0.0            0   
4  ...                     32          0.0          0.0            0   

    Active Min  Idle Mean   Idle Std   Idle Max   Idle Min   Label  
0            0        0.0        0.0          0          0       0  
1            0        0.0        0.0          0          0       0  
2            0        0.0        0.0          0          0       0  
3            0        0.0        0.0          0          0       0  
4            0        0.0        0.0          0          0       0  

[5 rows x 79 columns]

# here 0 = benign ,1 = dos golden eye,2= dos hulk ,3= dos slowhttptest 

In [12]:
from sklearn.feature_selection import SelectKBest,chi2
from sklearn.model_selection import train_test_split

In [13]:
Target= ' Label'
X = df.loc[:, df.columns != Target]
y = df.loc[:,Target]

In [14]:
from sklearn.impute import SimpleImputer
lower_bound=0
upper_bound=100
X_clipped = np.clip(X, lower_bound, upper_bound) 
imputer = SimpleImputer(strategy='mean')
X_imputed = imputer.fit_transform(X_clipped)

In [15]:
selector = SelectKBest(score_func=chi2, k=10)
selector.fit(X_imputed, y)
selected_features = selector.get_support(indices=True)
X_new = X_imputed[:, selected_features]
X_new_train, X_test, y_train, y_test = train_test_split(X_new, y, test_size=0.25)

In [16]:
print(selected_features)

[ 9 11 13 27 37 70 73 74 76 77]


In [17]:
X_new

array([[  0.        ,   6.        ,   0.        , ...,   0.        ,
          0.        ,   0.        ],
       [ 31.4492376 ,   0.        ,  89.27877687, ...,   0.        ,
          0.        ,   0.        ],
       [100.        ,   0.        , 100.        , ...,   0.        ,
          0.        ,   0.        ],
       ...,
       [ 21.92031022,   6.        ,   0.        , ...,   0.        ,
          0.        ,   0.        ],
       [  0.        , 100.        ,   0.        , ...,   0.        ,
          0.        ,   0.        ],
       [  0.        , 100.        ,   0.        , ...,   0.        ,
          0.        ,   0.        ]])

In [18]:
y.unique()

array([0, 4, 3, 2, 1, 5])

In [19]:
from sklearn.tree import DecisionTreeRegressor
dtr=DecisionTreeRegressor()
dtr.fit(X_new_train,y_train)

DecisionTreeRegressor()

In [20]:
y_pred=dtr.predict(X_test)

In [21]:
y_pred[:10]

array([1.99730458, 0.        , 1.98208955, 0.        , 1.25373571,
       0.        , 1.25373571, 0.        , 2.        , 1.25373571])

In [22]:
y_test[:10]

305209    2
421338    0
303293    2
488414    0
318101    2
393581    0
411768    0
30208     0
77545     2
296323    0
Name:  Label, dtype: int64

In [23]:
from sklearn .metrics import mean_squared_error


In [24]:
mean_squared_error( y_test,y_pred)

0.29577993381867684

In [25]:
from sklearn.ensemble import RandomForestRegressor

In [26]:
rf_reg=RandomForestRegressor(n_estimators=500 )
rf_reg.fit(X_new_train,y_train)

RandomForestRegressor(n_estimators=500)

In [27]:
y_pred=rf_reg.predict(X_test)

In [30]:
y_pred

array([1.99711407, 0.        , 1.98182917, ..., 0.        , 0.        ,
       0.        ])

In [34]:
y_pred = pd.DataFrame(data=y_pred,columns=['pred'])
pred

pred
0       1.997114
1       0.000000
2       1.981829
3       0.000000
4       1.253588
...          ...
173171  1.253588
173172  0.000000
173173  0.000000
173174  0.000000
173175  0.000000

[173176 rows x 1 columns]

In [36]:
mean_squared_error(y_test,y_pred)

TypeError: 'tuple' object is not callable

In [33]:
y_test

305209    2
421338    0
303293    2
488414    0
318101    2
         ..
172485    2
610141    0
394107    0
25196     0
315107    0
Name:  Label, Length: 173176, dtype: int64

In [ ]:
print(mean_squared_error)